### ISSUE TITLE
Multi loggers

### ISSUE THREAD

**Issue by KingLucius** [jirkapenzes/SimpleLogger#5]
Hello,
I have a list of classes, I want to add a file handler logger for each class which will save class's log into a file with name "log_class.log".
how can I do it by SimpleLogger, and Thanks for this great and simple lib ;)

Best regards,
Lucius23

**Comment by dptechdev** [comment]
So are you wanting to initiate a new file logger handler multiple times in each class? So that you can have multiple log files from each of the classes instead of just having one log file with all the logs of the different classes? I would be interested to know if you could just initiate a new file handler any time and have multiple log files or if the handlers are managed globally there can only be one log file at any give time.
